name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📂 Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r apps/backend/requirements.txt
          pip install pytest httpx

      - name: 🧪 Run tests
        run: |
          source venv/bin/activate
          pytest apps/backend/tests

# Download your code
# Set up Python (version 3.11)
# Install your backend dependencies from requirements.txt
# Run your test files in apps/backend/tests
# Show whether everything passed or not if any tests failed