services:
  backend:
    build: ../apps/backend         # Path from the compose file to the backend code
    ports:
      - "8000:8000"               # Map container 8000 -> host 8000
    volumes:
      - ../apps/backend:/app      # Mount code into container for live reloads
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
